export const tools = [
  {
    name: "createStickyNote",
    description: "Create a sticky note on the board",
    input_schema: {
      type: "object",
      properties: {
        id:    { type: "string", description: "Short ref key (e.g. 'note1') — used only to link connectors, real UUID is generated by the client" },
        text:  { type: "string" },
        x:     { type: "number" },
        y:     { type: "number" },
        color: { type: "string", enum: ["yellow", "pink", "blue", "green", "orange", "purple"] }
      },
      required: ["text", "x", "y", "color"]
    }
  },
  {
    name: "createShape",
    description: "Create a rectangle, circle, or line",
    input_schema: {
      type: "object",
      properties: {
        id:        { type: "string", description: "Short ref key for connector linking" },
        shapeType: { type: "string", enum: ["rectangle", "circle", "line"] },
        x:         { type: "number" },
        y:         { type: "number" },
        width:     { type: "number" },
        height:    { type: "number" },
        color:     { type: "string", enum: ["red", "blue", "green", "yellow", "orange", "purple", "gray", "white"] }
      },
      required: ["shapeType", "x", "y", "width", "height", "color"]
    }
  },
  {
    name: "createFrame",
    description: "Create a labeled frame to group content",
    input_schema: {
      type: "object",
      properties: {
        id:     { type: "string", description: "Short ref key for connector linking" },
        title:  { type: "string" },
        x:      { type: "number" },
        y:      { type: "number" },
        width:  { type: "number" },
        height: { type: "number" }
      },
      required: ["title", "x", "y", "width", "height"]
    }
  },
  {
    name: "createTextBox",
    description: "Create a standalone text element on the board",
    input_schema: {
      type: "object",
      properties: {
        id:       { type: "string", description: "Short ref key for connector linking" },
        text:     { type: "string" },
        x:        { type: "number" },
        y:        { type: "number" },
        fontSize: { type: "number" },
        color:    { type: "string" }
      },
      required: ["text", "x", "y"]
    }
  },
  {
    name: "createConnector",
    description: "Draw a connector arrow between two objects",
    input_schema: {
      type: "object",
      properties: {
        fromId: { type: "string", description: "Ref key of the source object" },
        toId:   { type: "string", description: "Ref key of the target object" },
        style:  { type: "string", enum: ["arrow", "line", "dashed"] }
      },
      required: ["fromId", "toId", "style"]
    }
  },
  {
    name: "moveObject",
    description: "Move an existing object to new coordinates",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string" },
        x:        { type: "number" },
        y:        { type: "number" }
      },
      required: ["objectId", "x", "y"]
    }
  },
  {
    name: "resizeObject",
    description: "Resize an existing object",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string" },
        width:    { type: "number" },
        height:   { type: "number" }
      },
      required: ["objectId", "width", "height"]
    }
  },
  {
    name: "updateStickyNoteText",
    description: "Change the text content of a sticky note",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string" },
        newText:  { type: "string" }
      },
      required: ["objectId", "newText"]
    }
  },
  {
    name: "updateTextBoxContent",
    description: "Change the text content of a standalone text box",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string" },
        newText:  { type: "string" }
      },
      required: ["objectId", "newText"]
    }
  },
  {
    name: "changeColor",
    description: "Change the color of an existing object",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string" },
        color:    { type: "string" }
      },
      required: ["objectId", "color"]
    }
  },
  {
    name: "getBoardState",
    description: "Returns current board state — already included in your context, no need to call this",
    input_schema: {
      type: "object",
      properties: {},
      required: []
    }
  },
  {
    name: "bulkCreateObjects",
    description: "Create many objects at once in a grid layout. Use this when the user asks for more than 5 of the same type of object (e.g. 'make 100 sticky notes', 'create 3000 stickies'). Much more efficient than calling individual create tools repeatedly.",
    input_schema: {
      type: "object",
      properties: {
        objectType: { type: "string", enum: ["sticky_note", "shape", "frame", "text"], description: "Type of object to create" },
        count: { type: "number", description: "Number of objects to create" },
        startX: { type: "number", description: "X coordinate of the top-left of the grid" },
        startY: { type: "number", description: "Y coordinate of the top-left of the grid" },
        columns: { type: "number", description: "Number of columns in the grid layout" },
        template: {
          type: "object",
          description: "Template for each created object",
          properties: {
            text: { type: "string", description: "Text content (supports {n} placeholder for 1-based index)" },
            color: { type: "string", description: "Color name or hex" },
            width: { type: "number" },
            height: { type: "number" },
            fontSize: { type: "number" },
            shapeType: { type: "string", enum: ["rectangle", "circle", "line"] },
            title: { type: "string", description: "For frames — supports {n} placeholder" },
          }
        }
      },
      required: ["objectType", "count", "startX", "startY", "columns", "template"]
    }
  },
  {
    name: "suggestFramework",
    description: "Suggest a coaching framework template to the coach. The framework will appear as a clickable suggestion chip — it does NOT auto-apply. Use this when the conversation topic aligns with a known framework (e.g. goal-setting → GROW, strengths analysis → SWOT).",
    input_schema: {
      type: "object",
      properties: {
        frameworkId: {
          type: "string",
          enum: ["grow", "swot", "wheelOfLife", "values", "okr"],
          description: "The template ID to suggest"
        },
        reason: {
          type: "string",
          description: "Brief explanation of why this framework fits the current discussion"
        }
      },
      required: ["frameworkId", "reason"]
    }
  },
  {
    name: "askClarification",
    description: "Ask the user a clarifying question when their request is ambiguous. Provide 2-4 suggestion options that become clickable buttons in the UI.",
    input_schema: {
      type: "object",
      properties: {
        question: { type: "string", description: "The clarifying question to ask the user" },
        suggestions: {
          type: "array",
          items: { type: "string" },
          description: "2-4 short suggestion options for the user to click",
          minItems: 2,
          maxItems: 4
        }
      },
      required: ["question", "suggestions"]
    }
  },
  {
    name: "createGoal",
    description: "Create a goal card for tracking coaching goals, commitments, and progress",
    input_schema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Short ref key for connector linking" },
        title: { type: "string", description: "Goal title" },
        commitments: {
          type: "array",
          items: { type: "string" },
          description: "List of specific commitments or action items for this goal"
        },
        due_date: { type: "string", description: "Optional due date in ISO format (YYYY-MM-DD)" },
        x: { type: "number" },
        y: { type: "number" }
      },
      required: ["title", "commitments", "x", "y"]
    }
  },
  {
    name: "updateGoalStatus",
    description: "Update the status of an existing goal (active, completed, stalled, or dropped)",
    input_schema: {
      type: "object",
      properties: {
        objectId: { type: "string", description: "The ID of the goal object to update" },
        status: { type: "string", enum: ["active", "completed", "stalled", "dropped"], description: "New status for the goal" },
        note: { type: "string", description: "Optional note explaining the status change" }
      },
      required: ["objectId", "status"]
    }
  },
  {
    name: "createSessionSummary",
    description: "Generate a structured summary of the current coaching session based on objects created and discussed. Creates a summary sticky note on the board.",
    input_schema: {
      type: "object",
      properties: {
        summary: { type: "string", description: "The session summary text" },
        keyThemes: {
          type: "array",
          items: { type: "string" },
          description: "Key themes identified during the session"
        },
        x: { type: "number" },
        y: { type: "number" }
      },
      required: ["summary", "keyThemes", "x", "y"]
    }
  },
  {
    name: "recallContext",
    description: "Search through past session summaries and AI memory to recall information from previous coaching sessions by topic",
    input_schema: {
      type: "object",
      properties: {
        topic: { type: "string", description: "The topic or keyword to search for in past sessions" }
      },
      required: ["topic"]
    }
  }
]
